# Generated by Django 6.0.2 on 2026-02-16 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_scores', models.FloatField()),
                ('attendance', models.FloatField()),
                ('hours_studied', models.FloatField()),
                ('tutoring_sessions', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='students.student')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
